version: '3.7'
services:
  shopapp-spring:    
    container_name: shopapp-spring-container    
    build:
      context: ./ecsb
      dockerfile: ../Dockerfile      
    ports:
      - 8088:8088
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopapp?serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - db
    networks:
      - shopapp-network

  db:
    container_name: mysql8-container
    image: mysql:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopapp
    ports:
      - 3307:3306
    volumes: 
      - ./database.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - shopapp-network
      
networks:
  shopapp-network:

#docker-compose -f deployment.yml build app
#docker-compose -f ./deployment.yml down
#docker-compose -f ./deployment.yml up -d db
#docker-compose -f ./deployment.yml up -d shopapp-spring
#test container 
#docker run -it --name openjdk-container maven:3.8.4-openjdk-17-slim

# view logs
# docker-compose -f deployment.yml logs -f shopapp-spring